"use client";

import {useEffect,useState} from "react";
import Link from "next/link";

export default function EnemyManagement(){
 const [enemies,setEnemies]=useState<any[]>([]);const [name,setName]=useState("");const [description,setDescription]=useState("");const [rank,setRank]=useState("NORMAL");const [weight,setWeight]=useState(1);const [boss,setBoss]=useState(false);const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/management/enemies");const text=await r.text();const d=text?JSON.parse(text):null;if(!r.ok)throw new Error(d?.error??"No se pudo cargar.");setEnemies(Array.isArray(d)?d:[]);}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar.");}}
 useEffect(()=>{load();},[]);
  async function create(){setError("");try{const r=await fetch("/api/management/enemies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,rank,encounterWeight:weight,isBoss:boss})});const text=await r.text();const d=text?JSON.parse(text):null;if(!r.ok)throw new Error(d?.error??"No se pudo crear.");setName("");setDescription("");setBoss(false);await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el enemigo.");}}
 return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-5xl px-6 py-8"><div className="flex justify-between"><div><h1 className="text-4xl font-bold">Catálogo de enemigos</h1><p className="mt-2 text-zinc-500">Los enemigos se instancian aleatoriamente al descubrir habitaciones.</p></div><Link href="/management" className="rounded-lg border border-zinc-700 px-4 py-2">← Gestión</Link></div>{error&&<p className="mt-5 text-red-300">{error}</p>}<section className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-6"><div className="grid gap-4 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre" className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"/><select value={rank} onChange={e=>setRank(e.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"><option>NORMAL</option><option>ELITE</option><option>BOSS</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descripción" className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3 md:col-span-2"/><label className="text-sm text-zinc-400">Peso<input type="number" min={1} value={weight} onChange={e=>setWeight(Math.max(1,Number(e.target.value)||1))} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"/></label><label className="flex items-center gap-3 pt-7"><input type="checkbox" checked={boss} onChange={e=>setBoss(e.target.checked)}/> Puede aparecer como jefe</label></div><button onClick={create} className="mt-4 rounded-lg bg-white px-5 py-3 font-medium text-black">Crear enemigo</button></section><div className="mt-8 grid gap-3">{enemies.map(e=><div key={e.id} className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4"><div className="flex justify-between"><span className="font-semibold">{e.name}</span><span className="text-xs text-zinc-500">{e.rank} · peso {e.encounterWeight}{e.isBoss?" · JEFE":""}</span></div><p className="mt-2 text-sm text-zinc-400">{e.description||"Sin descripción."}</p></div>)}</div></div></main>;
}
