"use client";

import {useEffect,useState} from "react";
import Link from "next/link";

type Theme={id:number;name:string;slug:string;description:string|null;active:boolean};
type Enemy={id:number;name:string;description:string|null;rank:string;encounterWeight:number;capturability:number;isBoss:boolean;imageUrl?:string|null;themeIds:number[];themes:Theme[]};

async function compress(file:File){
 const bitmap=await createImageBitmap(file), size=256, canvas=document.createElement("canvas"); canvas.width=size;canvas.height=size;
 const ctx=canvas.getContext("2d");if(!ctx)throw new Error("No se pudo preparar la imagen.");
 const scale=Math.max(size/bitmap.width,size/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;
 ctx.drawImage(bitmap,(size-w)/2,(size-h)/2,w,h);bitmap.close();
 return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("No se pudo comprimir.")),"image/webp",.82));
}

export default function EnemyManagement(){
 const [enemies,setEnemies]=useState<Enemy[]>([]),[drafts,setDrafts]=useState<Record<number,{themeIds:number[];capturability:number}>>({}),[themes,setThemes]=useState<Theme[]>([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[rank,setRank]=useState("NORMAL"),[weight,setWeight]=useState(1),[capturability,setCapturability]=useState(0),[boss,setBoss]=useState(false),[themeIds,setThemeIds]=useState<number[]>([]),[error,setError]=useState(""),[defaultImage,setDefaultImage]=useState<string|null>(null),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch("/api/management/enemies",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d?.error??"No se pudo cargar.");setEnemies(d.enemies??[]);setDrafts(Object.fromEntries((d.enemies??[]).map((e:Enemy)=>[e.id,{themeIds:e.themeIds??[],capturability:e.capturability??0}])));setDefaultImage(d.defaultImageUrl??null);const tr=await fetch("/api/management/themes",{cache:"no-store"});const td=await tr.json();if(tr.ok)setThemes(Array.isArray(td)?td.filter((t:Theme)=>t.active):[]);}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar.");}}
 useEffect(()=>{load();},[]);
 async function create(){setBusy(true);setError("");try{const r=await fetch("/api/management/enemies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,rank,encounterWeight:weight,capturability,isBoss:boss,themeIds})}),d=await r.json();if(!r.ok)throw new Error(d?.error??"No se pudo crear.");setName("");setDescription("");setBoss(false);setWeight(1);setCapturability(0);setThemeIds([]);await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo crear.");}finally{setBusy(false);}}
 async function saveEnemyConfig(enemy:Enemy){
  const draft=drafts[enemy.id]??{themeIds:enemy.themeIds??[],capturability:enemy.capturability??0};
  setBusy(true);setError("");
  try{
    const r=await fetch("/api/management/enemies/"+enemy.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({themeIds:draft.themeIds,capturability:draft.capturability})});
    const d=await r.json();if(!r.ok)throw new Error(d?.error??"No se pudo guardar.");
    setEnemies(v=>v.map(e=>e.id===enemy.id?{...e,...d,themeIds:draft.themeIds,capturability:draft.capturability,themes:themes.filter(t=>draft.themeIds.includes(t.id))}:e));
  }catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}finally{setBusy(false);}
 }
 async function upload(file:File,enemyId?:number){setBusy(true);setError("");try{const form=new FormData();form.append("file",await compress(file),"enemy.webp");if(enemyId)form.append("enemyId",String(enemyId));else form.append("default","true");const r=await fetch("/api/management/enemies/image",{method:"POST",body:form});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null;}catch{throw new Error("El servidor devolvió un error al subir la imagen ("+r.status+").");}if(!r.ok)throw new Error(d?.error??"No se pudo subir la imagen.");await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo subir.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-5xl px-6 py-8"><div className="flex justify-between gap-4"><div><h1 className="text-4xl font-bold">Catálogo de enemigos</h1><p className="mt-2 text-zinc-500">Los enemigos se instancian aleatoriamente al descubrir habitaciones.</p></div><Link href="/management" className="rounded-lg border border-zinc-700 px-4 py-2">← Gestión</Link></div>{error&&<p className="mt-5 rounded-lg border border-red-900/60 bg-red-950/30 p-3 text-red-300">{error}</p>}
 <section className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-6"><div className="grid gap-4 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre" className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"/><select value={rank} onChange={e=>setRank(e.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"><option>NORMAL</option><option>ELITE</option><option>BOSS</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descripción" className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3 md:col-span-2"/><label className="text-sm text-zinc-400">Peso<input type="number" min={1} value={weight} onChange={e=>setWeight(Math.max(1,Number(e.target.value)||1))} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"/></label><label className="text-sm text-zinc-400">Capturabilidad<input type="number" min={0} value={capturability} onChange={e=>setCapturability(Math.max(0,Number(e.target.value)||0))} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3"/><span className="text-xs text-zinc-600">0 = no capturable.</span></label><label className="flex items-center gap-3 pt-7"><input type="checkbox" checked={boss} onChange={e=>setBoss(e.target.checked)}/> Puede aparecer como jefe</label><div className="md:col-span-2"><p className="text-sm text-zinc-400">Temáticas</p><div className="mt-2 flex flex-wrap gap-2">{themes.map(t=><button type="button" key={t.id} onClick={()=>setThemeIds(v=>v.includes(t.id)?v.filter(id=>id!==t.id):[...v,t.id])} className={"rounded-full border px-3 py-1.5 text-xs "+(themeIds.includes(t.id)?"border-violet-400 bg-violet-400/15 text-violet-200":"border-zinc-700 text-zinc-400")}>{t.slug==="TODAS"?"🌐 ":""}{t.name}</button>)}</div><p className="mt-1 text-xs text-zinc-600">Sin selección = sin temática. General solo aparece en laberintos sin temática; Todas aparece en cualquier laberinto.</p></div></div><button onClick={create} disabled={busy||!name.trim()} className="mt-4 rounded-lg bg-white px-5 py-3 font-medium text-black disabled:opacity-40">{busy?"Procesando...":"Crear enemigo"}</button></section>
 <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Imagen genérica</h2><p className="text-xs text-zinc-500">Se usa si el enemigo no tiene imagen propia.</p></div><label className="cursor-pointer rounded-lg border border-zinc-700 px-3 py-2 text-sm">Subir/cambiar<input type="file" accept="image/*" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value="";}}/></label></div>{defaultImage?<img src={defaultImage} alt="" className="mt-3 h-20 w-20 rounded-lg object-cover"/>:<p className="mt-3 text-sm text-zinc-600">No configurada.</p>}</section>
 <div className="mt-8 grid gap-3">{enemies.map(e=><div key={e.id} className="flex items-center gap-4 rounded-xl border border-zinc-800 bg-zinc-900/40 p-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-lg border border-zinc-700 bg-zinc-950">{e.imageUrl||defaultImage?<img src={e.imageUrl??defaultImage??""} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[10px] text-zinc-600">Sin imagen</div>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><span className="font-semibold">{e.name}</span><span className="text-xs text-zinc-500">{e.rank} · peso {e.encounterWeight}{e.isBoss?" · JEFE":""}</span></div><p className="mt-1 text-sm text-zinc-400">{e.description||"Sin descripción."}</p><div className="mt-2 flex flex-wrap gap-1.5">{themes.map(t=>{const draft=drafts[e.id]??{themeIds:e.themeIds??[],capturability:e.capturability??0};return <button type="button" key={t.id} onClick={()=>setDrafts(v=>({...v,[e.id]:{...draft,themeIds:draft.themeIds.includes(t.id)?draft.themeIds.filter(id=>id!==t.id):[...draft.themeIds,t.id]}}))} className={"rounded-full border px-2 py-0.5 text-[11px] "+(draft.themeIds.includes(t.id)?"border-violet-400 bg-violet-400/15 text-violet-200":"border-zinc-700 text-zinc-500")}>{t.slug==="TODAS"?"🌐 ":""}{t.name}</button>})}<label className="flex items-center gap-1 text-[11px] text-zinc-500">Captura<input type="number" min={0} value={(drafts[e.id]??{themeIds:e.themeIds??[],capturability:e.capturability??0}).capturability} onChange={ev=>setDrafts(v=>({...v,[e.id]:{...(v[e.id]??{themeIds:e.themeIds??[]}),capturability:Math.max(0,Number(ev.target.value)||0)}}))} className="w-16 rounded border border-zinc-700 bg-zinc-950 px-1.5 py-0.5 text-white"/></label><button type="button" onClick={()=>saveEnemyConfig(e)} disabled={busy} className="rounded-full border border-emerald-900/60 px-2 py-0.5 text-[11px] text-emerald-300">Guardar</button></div></div><label className="cursor-pointer rounded-lg border border-zinc-700 px-3 py-2 text-xs">Imagen<input type="file" accept="image/*" className="hidden" disabled={busy} onChange={ev=>{const f=ev.target.files?.[0];if(f)upload(f,e.id);ev.currentTarget.value="";}}/></label></div>)}</div></div></main>;
}
