CREATE TABLE IF NOT EXISTS public."ruleSection" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "content" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "ruleSection_position_idx"
  ON public."ruleSection" ("position", "id");

ALTER TABLE public."ruleSection" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ruleSection_public_read" ON public."ruleSection";
CREATE POLICY "ruleSection_public_read"
  ON public."ruleSection"
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT SELECT ON public."ruleSection" TO anon, authenticated;
