create table if not exists public."auditLog" (
  "id" bigint generated by default as identity primary key,
  "actorUserId" integer references public."user"("id") on delete set null,
  "action" text not null,
  "entityType" text not null,
  "entityId" integer,
  "characterId" integer references public."character"("id") on delete set null,
  "targetUserId" integer references public."user"("id") on delete set null,
  "details" text,
  "createdAt" timestamptz not null default now()
);

create index if not exists "auditLog_createdAt_idx" on public."auditLog" ("createdAt" desc);
create index if not exists "auditLog_actorUserId_idx" on public."auditLog" ("actorUserId");
create index if not exists "auditLog_action_idx" on public."auditLog" ("action");
create index if not exists "auditLog_entityType_entityId_idx" on public."auditLog" ("entityType", "entityId");
create index if not exists "auditLog_characterId_idx" on public."auditLog" ("characterId");

alter table public."auditLog" enable row level security;
