create table if not exists public."race" (
  "id" integer generated by default as identity primary key,
  "name" text not null unique,
  "description" text,
  "imagePath" text,
  "active" boolean not null default true,
  "createdAt" timestamptz not null default now()
);

create table if not exists public."racePerk" (
  "raceId" integer not null references public."race"("id") on delete cascade,
  "perkId" integer not null references public."perk"("id") on delete restrict,
  "createdAt" timestamptz not null default now(),
  primary key ("raceId", "perkId")
);

alter table public."character"
  add column if not exists "raceId" integer references public."race"("id") on delete set null;

create index if not exists "racePerk_perkId_idx" on public."racePerk"("perkId");
create index if not exists "character_raceId_idx" on public."character"("raceId");

alter table public."race" enable row level security;
alter table public."racePerk" enable row level security;

drop policy if exists "race_select" on public."race";
create policy "race_select" on public."race"
  for select to anon, authenticated
  using ("active" = true);

drop policy if exists "racePerk_select" on public."racePerk";
create policy "racePerk_select" on public."racePerk"
  for select to anon, authenticated
  using (
    exists (
      select 1 from public."race" r
      where r."id" = "racePerk"."raceId" and r."active" = true
    )
  );
