create table if not exists public."theme" (
  "id" integer generated by default as identity primary key,
  "name" text not null,
  "slug" text not null,
  "description" text,
  "active" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  constraint "theme_name_key" unique ("name"),
  constraint "theme_slug_key" unique ("slug")
);

create table if not exists public."enemyTheme" (
  "enemyId" integer not null,
  "themeId" integer not null,
  constraint "enemyTheme_pkey" primary key ("enemyId","themeId"),
  constraint "enemyTheme_enemyId_fkey" foreign key ("enemyId") references public."enemy"("id") on delete cascade,
  constraint "enemyTheme_themeId_fkey" foreign key ("themeId") references public."theme"("id") on delete cascade
);

create table if not exists public."mazeTheme" (
  "mazeId" integer not null,
  "themeId" integer not null,
  constraint "mazeTheme_pkey" primary key ("mazeId","themeId"),
  constraint "mazeTheme_mazeId_fkey" foreign key ("mazeId") references public."maze"("id") on delete cascade,
  constraint "mazeTheme_themeId_fkey" foreign key ("themeId") references public."theme"("id") on delete cascade
);

alter table public."enemy" add column if not exists "capturability" integer not null default 0;
alter table public."enemy" add constraint "enemy_capturability_nonnegative" check ("capturability" >= 0);
